services:
  nxt2nxtdns:
    image: dheerusuthar/nxt2nxtdns:latest
    container_name: nxt2nxtdns
    restart: always
    ports:
      - "3000:3000"
    environment:
      MASTER_PASSWORD: ${MASTER_PASSWORD:-masterp@ss}
      JWT_SECRET: ${JWT_SECRET:-jwtSectret}
      DB_PATH: /app/data/app.db
    volumes:
      - nxt2nxtdns-data:/app/data